[Service]
Environment=OS_CONFIG_DIR=/home/leehojun/skyline-apiserver-extenstion/etc
Environment=SKYLINE_ENV=production
Environment=PYTHONDONTWRITEBYTECODE=1

ExecStart=
ExecStart=/home/leehojun/skyline/bin/uvicorn --host 127.0.0.1 --port 28000 --log-level info skyline_apiserver.main:app

UMask=0077
ProtectSystem=full
ProtectHome=read-only
PrivateDevices=true
ProtectKernelTunables=true
ProtectKernelModules=true
ProtectControlGroups=true
RestrictSUIDSGID=true
LockPersonality=true
